apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongodb-deployement
  name: mongodb-deployement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-deployement
  template:
    metadata:
      labels:
        app: mongodb-deployement
    spec:
      containers:
      - image: mongo
        name: mongodb
        ports:
         - containerPort: 27017
        volumeMounts: 
        - mountPath: /data/db
          name: mongostorage
        env: 
         - name: MONGO_INITDB_ROOT_USERNAME
           valueFrom:
            secretKeyRef: 
             name: mongodb-secret 
             key:  mongo-root-username
         - name: MONGO_INITDB_ROOT_PASSWORD
           valueFrom:
            secretKeyRef: 
             name: mongodb-secret 
             key:  mongo-root-password 
      volumes:
      - name: mongostorage
        persistentVolumeClaim:
          claimName: mongo-pvc
